version: '3.8'

services:

  tts:
    image: sel9371/daeun:tts
    container_name: tts
    ports:
      - ${TTS_PORT}:80
    volumes:
      - ${LOG_PATH}:/app/logs
    environment:
      MELO_DEVICE: ${MELO_DEVICE}